// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CampaignSessionSubscriptionController from "./campaign_session_subscription_controller"
application.register("campaign-session-subscription", CampaignSessionSubscriptionController)

import WizardController from "./wizard_controller"
application.register("wizard", WizardController)
